# version of docker engine
version: "3.5"

networks:
    api:
        driver: ${NETWORKS_DRIVER}

volumes:
    mariadb:
        driver: ${VOLUMES_DRIVER}
    adminer:
        driver: ${VOLUMES_DRIVER}
    redis:
        driver: ${VOLUMES_DRIVER}

services:
    app:
        build:
            context: ./php-fpm/api
        container_name: ${APP_NAME}
        volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        restart: unless-stopped
        tty: true
        expose:
            - "9000"
        networks:
            - api
    # nginx:
    #     build:
    #         context: ./nginx
    #         args:
    #             - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
    #             - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    #     container_name: ${APP_NAME}_nginx
    #     volumes:
    #     - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    #     - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
    #     - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    #     - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    #     restart: unless-stopped
    #     ports:
    #     - "${NGINX_HOST_HTTP_PORT}:80"
    #     - "${NGINX_HOST_HTTPS_PORT}:443"
    #     depends_on:
    #     - app
    #     networks:
    #     - backend
